name: Notify central CI

# Triggers only on tag pushes (tags: ["*"]).
# Uses a conditional check (if:) to ensure the tag was pushed from main:
# startsWith(github.ref, 'refs/tags/') ensures the event is a tag push.
# github.event.base_ref == 'refs/heads/main' ensures the tag was created from the main branch.

on:
  push:
    tags:
      - "*"  # Triggers only when a tag is pushed

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && github.event.base_ref == 'refs/heads/main'    
    steps:
      - name: Call central pipeline
        env:
          TARGET_REPO: bsm-cibot/bsm-ci-pipeline
          PAT: ${{ secrets.CI_DISPATCH_TOKEN }}  # see below
        run: |
          curl -s -X POST \
            -H "Authorization: token $PAT" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/$TARGET_REPO/dispatches \
            -d '{"event_type": "base-image-released", "client_payload": { "caller": "'"$GITHUB_REPOSITORY"'", "ref": "'"$GITHUB_SHA"'" }}'
            
