name: Notify central CI

on: [push, pull_request]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Call central pipeline
        env:
          TARGET_REPO: cibot/ci-pipeline
          PAT: ${{ secrets.CI_DISPATCH_TOKEN }}  # see below
        run: |
          curl -s -X POST \
            -H "Authorization: token $PAT" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/$TARGET_REPO/dispatches \
            -d '{"event_type": "build", "client_payload": { "caller": "'"$GITHUB_REPOSITORY"'", "ref": "'"$GITHUB_SHA"'" }}'
            
